In [1]:
%load_ext autoreload
%autoreload 2 

In [26]:
import numpy as np
import torch

In [6]:
b = []
c = []
for _ in range(100):
    b.append(torch.rand((3, 3)))
    c.append(torch.rand((3, 3)))

In [12]:
b = torch.stack(b)
c = torch.stack(c)

In [23]:
b[0]

tensor([[0.7747, 0.7950, 0.2838],
        [0.3128, 0.8400, 0.9861],
        [0.2274, 0.7249, 0.8541]])

In [18]:
b[0] - c[0]

tensor([[ 0.2450,  0.7736,  0.0769],
        [-0.0548,  0.1017,  0.0047],
        [ 0.0540,  0.5196, -0.0578]])

In [27]:
torch.norm(c[0])

tensor(1.6943)

In [29]:
torch.norm(b[0])

tensor(2.0964)

In [39]:
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)


In [40]:
cos(b[0] , c[0])

tensor([0.7455, 0.9968, 0.8899])

AttributeError: 'Tensor' object has no attribute 'dims'